/*
 * TaskDialog.java
 *
 * Created on 14. maaliskuuta 2003, 19:05
 */

package checkmate.gui;

import checkmate.model.Task;
import checkmate.recorder.Recorder;
/**
 *
 * @author  jitkonen
 */
public class TaskDialog extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
	private Task task = null;
    private Recorder recorder = null;
    /** Creates new form TaskDialog */
    public TaskDialog(java.awt.Frame parent, Task currentTask, Recorder rec) {
        super(parent, true);
        task = currentTask;
        recorder = rec;
        initComponents();
        initTask();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        titlePanel = new javax.swing.JPanel();
        taskTitleLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minuteField = new javax.swing.JTextField();

        setTitle("Add manual entry");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        taskTitleLabel.setText("Task 1");
        titlePanel.add(taskTitleLabel);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        createButton.setText("Create manual entry");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(createButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jLabel1.setText(" Recorded time (minutes)");
        dataPanel.add(jLabel1);

        minuteField.setText("");
        minuteField.setPreferredSize(new java.awt.Dimension(40, 21));
        minuteField.setMinimumSize(new java.awt.Dimension(40, 21));
        minuteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        dataPanel.add(minuteField);

        getContentPane().add(dataPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    private void initTask() {
        taskTitleLabel.setText(task.toString());
    }
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        int min = Integer.valueOf(minuteField.getText()).intValue();
        recorder.addManualEntry(min, task);
        closeDialog(null);
    }//GEN-LAST:event_createButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        task = null;
        dispose();
        
    }//GEN-LAST:event_closeDialog
           
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel taskTitleLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JTextField minuteField;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
    
}
